from aiogram import types

markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
BTC = types.KeyboardButton("BTC")
ETH = types.KeyboardButton("ETH")
USDT = types.KeyboardButton("USDT")
USDC = types.KeyboardButton("USDC")
BNB = types.KeyboardButton("BNB")
XRP = types.KeyboardButton("XRP")
BUSD = types.KeyboardButton("BUSD")
ADA = types.KeyboardButton("ADA")
DOGE = types.KeyboardButton("DOGE")
MATIC = types.KeyboardButton("MATIC")
LINK = types.KeyboardButton("LINK")
DOT = types.KeyboardButton("DOT")
SOL = types.KeyboardButton("SOL")
LTC = types.KeyboardButton("LTC")
SHIB = types.KeyboardButton("SHIB")
WETH = types.KeyboardButton("WETH")
TRX = types.KeyboardButton("TRX")
DAI = types.KeyboardButton("DAI")
UNI = types.KeyboardButton("UNI")
AVAX = types.KeyboardButton("AVAX")
BIT = types.KeyboardButton("BIT")
ATOM = types.KeyboardButton("ATOM")
WBTC = types.KeyboardButton("WBTC")
TON = types.KeyboardButton("TON")
XMR = types.KeyboardButton("XMR")
ETC = types.KeyboardButton("ETC")
HT = types.KeyboardButton("HT")
LDO = types.KeyboardButton("LDO")
BCH = types.KeyboardButton("BCH")
TWT = types.KeyboardButton("TWT")
XLM = types.KeyboardButton("XLM")
ALGO = types.KeyboardButton("ALGO")
WSTETH = types.KeyboardButton("WSTETH")
FRAX = types.KeyboardButton("FRAX")
ENS = types.KeyboardButton("ENS")
VET = types.KeyboardButton("VET")
ICP = types.KeyboardButton("ICP")
FIL = types.KeyboardButton("FIL")
CAKE = types.KeyboardButton("CAKE")
QNT = types.KeyboardButton("QNT")
SAND = types.KeyboardButton("SAND")
HBAR = types.KeyboardButton("HBAR")
LUNC = types.KeyboardButton("LUNC")
FXS = types.KeyboardButton("FXS")
NEAR = types.KeyboardButton("NEAR")
CRO = types.KeyboardButton("CRO")
IMX = types.KeyboardButton("IMX")
AAVE = types.KeyboardButton("AAVE")
x = markup.add(BTC, ETH, USDT, USDC, BNB, XRP, BUSD, ADA, DOGE, MATIC, LINK, DOT, SOL, LTC, SHIB, WETH, TRX, DAI, UNI,
               AVAX,
               BIT, ATOM, WBTC, TON, XMR, ETC, HT, LDO, BCH, TWT, XLM, ALGO, WSTETH, FRAX, ENS, VET, ICP, FIL, CAKE,
               QNT,
               SAND, HBAR, LUNC, FXS, NEAR, CRO, IMX, AAVE)
